- extensions/dirvish-extras.el
- remove `file-truename`
`file-attribute-size` with symbolic link that points to nonexistent
file return `nil`, which may break `dirvish--get-file-size-or-count`.
> fix(extras): file-size-human-readable wrong-type-argument `nil`

- dirvish.el
Windows 环境变量的分隔符是反斜杠，直接使用会导致 replace-regexp-in-string 函数出错无法显示 header
> fix(core): get $HOME variable as directory

- extensions/dirvish-emerge.el
Small change as in the title.
BTW, there is on remaining issue with the highlighting. If I hide a group and then move to the next next group title, it is not highlighted. But I can highlight it if I press any key for moving to the right.
> Only insert group title for non empty groups

- dirvish.el
The change to `dirvish--render-attributes` fixes the problem  thatif there are two many hidden lines on the screen the visible lines after them don't get their attributes rendered. This happens for example when a group with large number of files is hidden.
The change to `dirvish-update-body-h` is because at least in my case there are two hidden lines at the top of the buffer one with the name of the directory and other containing its size. Sometimes when beginning of buffer is hit the cursor gets stuck at the beginning of second visible line the first time. `(forward-line 2)` would be another solution but I am not sure if everyone has the same 2 lines at the beginning.
> Only consider visible lines when rendering attributes

- dirvish.el
I ran into some issues with the git-msg on files with spaces in the
names. I've just added a small fix to help with that.
> shell quote filenames for git-msg

- dirvish.el
I've just edited the advice for entering `wdired-mode` to set the hollow
cursor. This way we can retain the clean look when normally using dirvish.
> use hollow cursor for evil normal state in wdired-mode

- extensions/dirvish-subtree.el
I figured it may be useful to have `dirvish-subtree-remove` as an
interactive function. Often I want to close a subtree when I'm a number
of rows below the beginning of the tree.
> make dirvish-subtree-remove an interactive function

- extensions/dirvish-fd.el
Some systems such as Debian name fd as fdfind, which is currently not handled by Dirvish.
This commit changes `dirvish-fd-program` do a custom variable, indicating the user it is possible to customize its value. When initializing the variable, it tries to look for either `fd` or
`fdfind` and set it as its default value. If neither is found, emit a warning about `fd` not being installed.
> Handle systems using fdfind by default

- dirvish.el
Hi, thank you for this package!
I often create a new file from `find-file`, and I felt `Preview for ... has been disabled` message incorrect for that 😅
> Produce detailed messages in disable preview

- extensions/dirvish-fd.el
By default, `dirvish-fd-jump` searches for all directories at the root of the filesystem. This commit adds a custom variable that can change this behaviour.
> New custom variable for default directory in dirvish-fd-jump

- extensions/dirvish-fd.el
If a call to `dirvish-fd-jump` is prefixed with `C-u` (for instance `C-u M-x dirvish-fd-jump`), find directories in the active directory only. Otherwise, search in the directory pointed at by `dirvish-fd-default-dir` (the current default behaviour).
> dirvish-fd-jump to search in current directory with C-u

- extensions/dirvish-fd.el
When prefixing the command `dirvish-fd-jump` with two `C-u` (e.g. `C-u C-u M-x dirvish-fd-jump`), the user can choose the directory from which to search other directories.
This does not modify the current behaviour of `dirvish-fd-jump` when prefixed with a simple `C-u` or not prefixed at all.
> Allow user to select root directory for `dirvish-fd-jump`

- extensions/dirvish-emerge.el
I had the same issue sometimes and this fixes it. I noticed that the overlays for the groups are still stored in `dirvish-emerge--group-overlays` though they appear as `overlay in no buffer` presumably because of revert.
P.S. I am somewhat surprised that reverting the buffer doesn't reset the buffer local variables.
> Fix #158 : Delete emerge overlays when turning off the mode

- dirvish-extras.el
- extensions/dirvish-subtree.el
As the byte-compiler points out, these condition symbols should not be quoted.
> fix(core): don't quote conditions in condition-case

- dirvish.el
- extensions/dirvish-icons.el
- extensions/dirvish-subtree.el
Add support for [nerd-icons](https://github.com/rainstormstudio/nerd-icons.el).
Now icons can be displayed on both GUI and terminal.
on terminal (with Nerd Fonts):
major configuration for using nerd-icons:
``` emacs-lisp
(setq dirvish-attributes
'(vc-state subtree-state nerd-icons collapse git-msg file-time file-size))
(setq dirvish-subtree-state-style 'nerd)
(note: I'm currently waiting for emacs-nerd-icons to be accepted on Melpa)
```
> add nerd-icons support

- dirvish.el
Emacs binary path is hardcoded for macOS. I changed it in a way that it is resolved dynamically and in case it fails, it still uses the old way of resolving the binary path.
I believe this fixes dirvish#189
> fix(core): resolve emacs binary path in a more reliable way

- extensions/dirvish-fd.el
I stumbled upon this  [error](https://github.com/sharkdp/fd/issues/1179) in fd.
But before this fix no actual error from fd was reported. Actually it was not helpful error in `dirvish-fd-proc-sentinel`:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
dirvish-fd--parse-output()
dirvish-fd-proc-sentinel(#<process fd> "exited abnormally with code 1\n")
```
Im not sure that it is the best way to handle errors, but at least It can save time when debugging original error.
> Report error from fd to user

- extensions/dirvish-yank.el
Im not sure,  is it intentional or not, but `dired-rsync` copied files locally using `dirvish-yank-default-handler`. I think its quite confusing.  I was expecting that `dired-rsync` uses  rsync for all scenarios.
> Use rsync for local file copying in dirvish-rsync

- extensions/dirvish-yank.el
I took inspiration from the great [dired-rsync-transient](https://github.com/stsquad/dired-rsync/blob/master/dired-rsync-transient.el).
I added some switches/groups. Also I added function `dirvish-yank--rsync-transient-init-value` which tries to provide previously saved switches. At first it looks in local dirvish session via `dirvish-prop`.  Then it checks if the switches are already set (they may be saved using `C-x s` keybinding for the whole emacs session). Then it tries to load saved switches (via `C-x C-s` transient command) and at the last resort returns switches from the defcustom `dirvish-yank-rsync-args`.
> Add rsync transient map

- extensions/dirvish-fd.el
Also don't use `dirvish-fd--narrow` on fd output, unless input pattern is empty.
The default behavior of `dirvish-fd` was not changed: it  spits out all directory content and starts `dirvish-fd-narrow`.
Rationale:
- filtering using emacs regex can be very slow on large number of fd output. Its better to filter as much as possible with the fast fd and if user needs fine-grade filtering he can use `dirvish-narrow`. For example on my `.local` directory that contains 150k files, it took forever to create `fd` output buffer.
- Some patterns that are supported by `fd` didn't work. For example `alt1|alt2` didn't work as expected.
> fd: add function that reads pattern from user

- dirvish.el
The line
```elisp
(format "%S" `(message "%s" ,(dirvish--dir-data-getter dir)))
```
Sometimes generates something like:
```elisp
(with-temp-buffer (let ((hash ...) (bk ...)) (dolist (file ...) (let* ... ... ...)) (prin1 (cons bk hash) (current-buffer))) (buffer-substring-no-properties (point-min) (point-max)))
```
which is then sent to `emacs -Q` to run but of course it fails to run because of the ellipses all over the code. These ellipses are managed by `print-length` and `print-level` variables which are when set to `nil` never generates ellipses.
Possibly we need to set these variables to `nil` whenever we generate code using `(format "%S")` but I haven't had any problems with other parts so far.
> Remove the restriction on printing for `dirvish-data-for-dir`

- extensions/dirvish-vc.el
This allows themes to apply styles that are suitable for Dirvish even when they would not necessarily look good in the modeline where the generic VC faces are present in.  For example, the modus-themes do not apply colours to the generic VC modeline faces, though they should apply colour-coding in Dirvish buffers.
> Define new faces for all VC states

- dirvish.el
Dired supports both strings and lists in dired-noselect.
``` elisp
(defun dired-noselect (dir-or-list &optional switches)
"Like `dired' but return the Dired buffer as value, do not select it."
(or dir-or-list (setq dir-or-list default-directory))
;; This loses the distinction between "/foo/*/" and "/foo/*" that
;; some shells make:
(let (dirname initially-was-dirname)
(if (consp dir-or-list)
(setq dirname (car dir-or-list))
(setq dirname dir-or-list))
(setq initially-was-dirname
(string= (file-name-as-directory dirname) dirname))
(setq dirname (abbreviate-file-name
(expand-file-name (directory-file-name dirname))))
(if find-file-visit-truename
(setq dirname (file-truename dirname)))
;; If the argument was syntactically  a directory name not a file name,
;; or if it happens to name a file …
```
> fix(dired-noselect): Support both lists and strings

- extensions/dirvish-yank.el
handle 3 different scenarios:
- destination host == source host
- destination host != source host
- direct connection from source host to destination
- creating tunnel for connecting source with destination
Whether to use direct connection is controlled by the global variable `dirvish-yank-r2r-default-direct-conn`, and by local one. 
Create Configure menu in `rsync-transient` that allows to tune various connection options to the destination host.
> refactor(yank): rework copying r2r case for rsync

- extensions/dirvish-subtree.el
Currently, `dirvish-subtree-toggle-or-open` utilizes `dirvish-subtree-toggle` to first attempt to toggle a directory line, then if that fails it assumes the current line represents a file and will attempt to open the file.  Unfortunately,
`dirvish-subtree-toggle` has an error handler, so if the directory toggle does fail it will view the file and not propagate the error. Since an error handler prevents the propagation of a directory toggle failure up to `dirvish-subtree-toggle-or-open`, the result is that when the current line represents a file, it will always be viewed instead of opened.
Instead of depending on error propagation when the line is not a directory, this change instead checks to see if the line represents a directory first.  When it is a directory, `dirvish-subtree-toggle` …
> fix(subtree): "toggle or open" should open file, not view it

- extensions/dirvish-yank.el
The used function is autoloaded, but the variable is not.
> fix(yank): silence byte-compiler

- dirvish.el
- docs/CHANGELOG.org
- docs/COMPARISON.org
- docs/CUSTOMIZING.org
- docs/EXTENSIONS.org
- extensions/dirvish-emerge.el
- extensions/dirvish-icons.el
- extensions/dirvish-ls.el
- extensions/dirvish-peek.el
- extensions/dirvish-subtree.el
- extensions/dirvish-vc.el
- extensions/dirvish-yank.el
On Emacs' "master" branch, the byte-compiler recently learned to recognize more common mistakes in custom type specifications.  This pull-requests fixes most of them, but there are two exceptions, you still have to find a solution for:
```
lib/dirvish/dirvish.el:190:29: Warning: in defcustom for ‘dirvish-open-with-programs’: irregular type ‘(repeat string)’
lib/dirvish/dirvish.el:191:31: Warning: in defcustom for ‘dirvish-open-with-programs’: irregular type ‘(repeat string)’
```
This pr also includes the commits from my earlier prs, #220 and #227.
> Fix custom type specifications

- dirvish.el
Took me quite some time to found how I could disable the additional windows when starting (see https://github.com/alexluigit/dirvish/issues/197). If you do not intend to change the code, I think this could be useful to more than me and should be documented. Hence this pull request.
> docs: document the nil case for dirvish-default-layout.

- extensions/dirvish-yank.el
It could be useful for overriding the code that creates external process for actual yank operations (rsync or copy/move).
For example, I override new method (dirvish-yank--start-proc) in my fork of detached.el library.
It allows me to detach execution of rsync command from the Emacs instance. Also detached.el provides better monitoring and alerting facilities.
> Split dirvish-yank--execute into two functions

- dirvish.el
When an emacsclient frame is created by visitng directory A, and then the user goes into subdirectory B and opens a file using dirvish-find-entry-a, the buffer for A no longer has a window and gets killed by dirvish-kill. Since this was the original buffer the client was opened with, this causes the client frame to be killed along with it, resulting in the frame going away instead of showing the file. This has been reported earlier in [0] and [1].
This can be reproduced by following the below steps mentioned in [0]:
mkdir tmp && cd tmp
mkdir dir
touch dir/foo
emacsclient -nw .
This will cause the frame to close instead of opening foo.
For buffers tied with a client, the variable server-buffer-clients is non-nil. Use that to detect such buffers and avoid killing them. Those buffers will be …
> fix: prevent killing emacsclient started on a directory

- extensions/dirvish-peek.el
Added a new variable `dirvish-peek-pre-cand` to track the previously displayed candidate. The peek window will now only update when the candidate changes, preventing redundant updates when navigating through directories. Also resets `dirvish-peek-pre-cand` when cleaning up peek sessions.
> perf(dirvish-peek): prevent redundant updates by tracking previous candidate

- docs/EXTENSIONS.org
- extensions/dirvish-side.el
This PR addresses the inability to manually resize the `dirvish-side` window (#332) due to its `window-size-fixed` property. It introduces dedicated interactive commands that allow users to increase or decrease the side window's width on demand without permanently changing the `dirvish-side-width` setting or disrupting the fixed-size behavior during automatic window management.
> feat(side): Add Commands for Manual Width Resizing

- dirvish-tramp.el
Hi!
Even though https://github.com/alexluigit/dirvish/pull/300 got closed, GVFS connections remain broken on my machine (`Wrong type argument: number-or-marker-p, nil`) - that's because calling `process-file` on those connections returns `nil`, and `(= nil 0)` ends up throwing this `Wrong type argument` error.
A simple solution is to coalesce `nil` into something else, e.g. `1`, simulating the command returning an error code.
> fix(tramp): don't call process-file for non-async connections
